name: lomo
description: A new Flutter application.
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.41+51
environment:
  sdk: '>=2.16.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^3.2.0
  json_annotation: ^4.0.1
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.9.0
  flutter_flavor: ^3.0.0
  http_parser: ^4.0.0
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.6
  provider: ^6.0.0
  dio: ^4.0.4
  get_it: ^7.1.3
  cached_network_image: ^3.2.1
  flutter_svg: ^0.23.0+1
  url_launcher: ^6.0.7
  fluttertoast: ^8.0.8
  device_info_plus: 3.2.4
  package_info: ^2.0.2
  sprintf: ^6.0.0
  diacritic: ^0.1.3
  share: ^2.0.4
  rxdart: ^0.27.1
  animated_widgets: ^1.1.0
  flutter_widget_from_html: ^0.8.2
  hashtagable: ^2.0.2
  geolocator: ^8.0.1
  event_bus: ^2.0.0
  photo_view: ^0.13.0
  permission_handler: ^8.1.1
  permission_handler_platform_interface: ^3.1.0
  webview_flutter: ^3.0.1
  screenshot: ^1.2.1
  carousel_slider: ^4.0.0
  flutter_image_compress: ^1.1.0
  flutter_cache_manager: ^3.1.2
  firebase_messaging: ^11.1.0
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  flutter_local_notifications: ^9.1.4
  firebase_crashlytics: ^2.0.6
  firebase_database: ^8.0.1
  flutter_slidable: ^0.6.0
  material_tag_editor: ^0.1.1
  dropdown_search: ^2.0.1
  flutter_portal: ^0.4.0
  appsflyer_sdk: ^6.4.0
  image_downloader: ^0.31.0
  image_cropper: ^1.5.1
  app_tracking_transparency: ^2.0.2+1
  dotted_border: ^2.0.0
  hive: ^2.0.4
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  step_progress_indicator: ^1.0.1
  keyboard_attachable: ^2.0.0
  image_picker: ^0.8.0+4
  shimmer: ^2.0.0
  connectivity: ^3.0.6
  collection: ^1.15.0
  diffutil_dart: ^3.0.0
  expandable: ^5.0.1
  octo_image: ^1.0.0+1
  socket_io_client: ^1.0.1
  flutter_keyboard_visibility: ^5.0.3
  navigation_history_observer: ^1.1.0
  percent_indicator: ^4.2.0
  visibility_detector: ^0.3.3
  # Gallary
  photo_manager: ^2.2.1
  camera: ^0.9.4+5
  video_thumbnail: ^0.5.2
  ffmpeg_kit_flutter: 4.5.1-LTS
  video_compress:
    git:
      url: https://github.com/jonataslaw/videoCompress.git
      ref: a14d392
  #video
  chewie: ^1.3.4
  audio_video_progress_bar: ^0.10.0
  android_path_provider: ^0.3.0
  inview_notifier_list: ^3.0.0
  app_settings: ^4.1.8

  intl_utils:
    path: ./intl_utils-master
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_intl:
  enable: true
  class_name: S
  arb_dir: lib/res/l10n
  output_dir: lib/res/l10n
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/mocks/
    - assets/json/
    - assets/fonts/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.otf
        - asset: assets/fonts/GoogleSans-Light.ttf
          weight: 300
        - asset: assets/fonts/GoogleSans-Medium.otf
          weight: 600
        - asset: assets/fonts/GoogleSans-Bold.otf
          weight: 700