import 'package:get_it/get_it.dart';
import 'package:lomo/app/app_model.dart';
import 'package:lomo/app/push_notification_manager.dart';
import 'package:lomo/app/user_model.dart';
import 'package:lomo/data/api/services/common_service.dart';
import 'package:lomo/data/api/services/new_feed_service.dart';
import 'package:lomo/data/api/services/notification_service.dart';
import 'package:lomo/data/api/services/user_service.dart';
import 'package:lomo/data/database/db_manager.dart';
import 'package:lomo/data/repositories/common_repository.dart';
import 'package:lomo/data/repositories/new_feed_repository.dart';
import 'package:lomo/data/repositories/notification_repository.dart';
import 'package:lomo/data/repositories/user_repository.dart';
import 'package:lomo/data/socket/socket_manager.dart';
import 'package:lomo/data/tracking/facebook_tracking.dart';
import 'package:lomo/data/tracking/tracking_manager.dart';
import 'package:lomo/libraries/photo_manager/photo_provider.dart';
import 'package:lomo/res/theme/theme_manager.dart';
import 'package:lomo/ui/authencation/birthday/birthday_model.dart';
import 'package:lomo/ui/authencation/display_name/display_name_model.dart';
import 'package:lomo/ui/authencation/gender/gender_model.dart';
import 'package:lomo/ui/authencation/image/image_model.dart';
import 'package:lomo/ui/checkin/list_checkin_model.dart';
import 'package:lomo/ui/cities/cities_model.dart';
import 'package:lomo/ui/comment/comment_children/comment_children_model.dart';
import 'package:lomo/ui/comment/comment_model.dart';
import 'package:lomo/ui/crop_image/crop_image_model.dart';
import 'package:lomo/ui/dating/create_dating_profile/add_information/add_information_create_dating_profile_model.dart';
import 'package:lomo/ui/dating/create_dating_profile/find_friend_create_dating_profile/find_friend_create_dating_profile_model.dart';
import 'package:lomo/ui/dating/create_dating_profile/review_information/review_information_create_dating_profile_model.dart';
import 'package:lomo/ui/dating/dating_list/dating_list_item_model.dart';
import 'package:lomo/ui/dating/dating_list/dating_list_model.dart';
import 'package:lomo/ui/dating/dating_user_detail/dating_user_detail_model.dart';
import 'package:lomo/ui/dating/filter/dating_filter_model.dart';
import 'package:lomo/ui/dating/first_message/first_message_model.dart';
import 'package:lomo/ui/dating/setting/dating_setting_model.dart';
import 'package:lomo/ui/dating/user_dating_basic_info_model.dart';
import 'package:lomo/ui/dating/verify_dating_image/verify_dating_image_model.dart';
import 'package:lomo/ui/dating/who_suits_me/profile/history/who_suits_me_history_model.dart';
import 'package:lomo/ui/dating/who_suits_me/profile/my_question/my_question_model.dart';
import 'package:lomo/ui/dating/who_suits_me/profile/result/who_suits_me_result_model.dart';
import 'package:lomo/ui/dating/who_suits_me/profile/review/review_quiz_result_model.dart';
import 'package:lomo/ui/dating/who_suits_me/profile/template_question/template_question_model.dart';
import 'package:lomo/ui/dating/who_suits_me/profile/who_suits_me_profile_model.dart';
import 'package:lomo/ui/dating/who_suits_me/reply_question/reply_question_item_model.dart';
import 'package:lomo/ui/dating/who_suits_me/reply_question/reply_question_model.dart';
import 'package:lomo/ui/discovery/discovery_model.dart';
import 'package:lomo/ui/discovery/event_slider_model.dart';
import 'package:lomo/ui/discovery/list_discovery/list_gift_discovery/list_gift_discovery_model.dart';
import 'package:lomo/ui/discovery/list_discovery/list_hot_model.dart';
import 'package:lomo/ui/discovery/list_discovery/list_knowledge/list_knowledge_model.dart';
import 'package:lomo/ui/discovery/list_discovery/list_more_hot/list_more_hot_model.dart';
import 'package:lomo/ui/discovery/list_discovery/list_more_topic/list_more_topic_model.dart';
import 'package:lomo/ui/discovery/list_discovery/list_topic_hot/list_topic_hot_model.dart';
import 'package:lomo/ui/discovery/list_more_out_standing/list_more_out_standing_model.dart';
import 'package:lomo/ui/discovery/list_type_discovery/list_type_discovery_model.dart';
import 'package:lomo/ui/discovery/newfeed/list_discovery/discovery_newfeeds_model.dart';
import 'package:lomo/ui/discovery/newfeed/list_more/discovery_newfeeds_more_model.dart';
import 'package:lomo/ui/discovery/out_standing_event_model.dart';
import 'package:lomo/ui/forgot_password/forgot_password_model.dart';
import 'package:lomo/ui/gift/exchange_gift/exchange_gift_model.dart';
import 'package:lomo/ui/gift/list_gift_model.dart';
import 'package:lomo/ui/gift/list_more_gift_model.dart';
import 'package:lomo/ui/gift/send_information_gift/send_information_gift_model.dart';
import 'package:lomo/ui/home/highlight/fliter_timeline/filter_timeline_model.dart';
import 'package:lomo/ui/home/highlight/highlight_model.dart';
import 'package:lomo/ui/home/highlight/post_detail/post_detail_model.dart';
import 'package:lomo/ui/home/highlight/post_detail/video_detail_model.dart';
import 'package:lomo/ui/home/highlight/timeline/item/timeline_item_model.dart';
import 'package:lomo/ui/home/highlight/timeline/list_favorite/favorite_post_model.dart';
import 'package:lomo/ui/home/highlight/timeline/timeline_list_model.dart';
import 'package:lomo/ui/home/home_model.dart';
import 'package:lomo/ui/introduce/intro_model.dart';
import 'package:lomo/ui/login/login_model.dart';
import 'package:lomo/ui/new_feed/create_new_feed/create_new_feed_model.dart';
import 'package:lomo/ui/new_feed/search_list_topic/topic_list_model.dart';
import 'package:lomo/ui/new_feed/video_resize/video_resize_model.dart';
import 'package:lomo/ui/notification/notification_detail/notification_detail_model.dart';
import 'package:lomo/ui/notification/notification_list/notification_list_model.dart';
import 'package:lomo/ui/otp/otp_model.dart';
import 'package:lomo/ui/profile/mypost/my_post_model.dart';
import 'package:lomo/ui/profile/person/person_follow/person_follow_model.dart';
import 'package:lomo/ui/profile/person/person_highlight_model.dart';
import 'package:lomo/ui/profile/person/person_message/person_message_model.dart';
import 'package:lomo/ui/profile/profile_candy/profile_candy_model.dart';
import 'package:lomo/ui/profile/profile_file/profile_file_model.dart';
import 'package:lomo/ui/profile/profile_manager/profile_detail/profile_detail_model.dart';
import 'package:lomo/ui/profile/profile_manager/profile_edit/profile_edit_model.dart';
import 'package:lomo/ui/profile/profile_manager/profile_gender/profile_gender_model.dart';
import 'package:lomo/ui/profile/profile_model.dart';
import 'package:lomo/ui/profile/profile_timeline/time_line_model.dart';
import 'package:lomo/ui/referral/enter_referral/enter_referral_model.dart';
import 'package:lomo/ui/register/register_model.dart';
import 'package:lomo/ui/search/search_hashtag/search_hashtag_model.dart';
import 'package:lomo/ui/search/search_model.dart';
import 'package:lomo/ui/search/search_new_feed/search_new_feed_model.dart';
import 'package:lomo/ui/search/search_theme/search_theme_model.dart';
import 'package:lomo/ui/search/search_user/search_user_model.dart';
import 'package:lomo/ui/settings/block_user/block_user_model.dart';
import 'package:lomo/ui/settings/privacy/privacy_model.dart';
import 'package:lomo/ui/settings/user_setting/user_setting_model.dart';
import 'package:lomo/ui/test_model.dart';
import 'package:lomo/ui/update_information/update_info_non_require_model.dart';
import 'package:lomo/ui/update_information/update_info_require_model.dart';
import 'package:lomo/ui/update_information/update_information_model.dart';
import 'package:lomo/ui/video/player/player_model.dart';
import 'package:lomo/ui/widget/bear/give_bear_widget_model.dart';
import 'package:lomo/ui/widget/flutter_in_app_web_view_model.dart';
import 'package:lomo/util/AppsflyerUtil.dart';
import 'package:lomo/util/firebase_realtime_database_util.dart';
import 'package:lomo/util/handle_link_util.dart';
import 'package:lomo/util/image_picker.dart';
import 'package:lomo/util/location_manager.dart';
import 'package:lomo/util/navigator_service.dart';
import 'package:lomo/util/permission_handle_manager.dart';
import 'package:lomo/util/platform_channel.dart';
import 'package:lomo/util/tool_tip_manager.dart';

import '../ui/discovery/near_you/near_you_model.dart';
import '../ui/notification/notification_voucher_detail/notification_voucher_detail_model.dart';
import '../ui/report/report_model.dart';
import '../ui/settings/delete_account/delete_account_model.dart';

final locator = GetIt.instance;

void setupLocator() {
  locator.registerLazySingleton(() => PlatformChannel());
  locator.registerLazySingleton(() => ThemeManager());

  locator.registerLazySingleton(() => NavigationService());
  locator.registerLazySingleton(() => AppModel());
  locator.registerLazySingleton(() => UserModel());
  locator.registerLazySingleton(() => PushNotificationManager());

  locator.registerLazySingleton(() => LocationManager());
  locator.registerLazySingleton(() => PermissionHandleManager());
  locator.registerLazySingleton(() => MyImagePicker());
  locator.registerLazySingleton(() => SocketManager());

  locator.registerLazySingleton(() => HandleLinkUtil());

  locator.registerLazySingleton(() => UserService());
  locator.registerLazySingleton(() => CommonService());
  locator.registerLazySingleton(() => NotificationService());
  locator.registerLazySingleton(() => NewFeedService());
  locator.registerLazySingleton(() => DbManager());

  locator.registerLazySingleton(() => UserRepository());
  locator.registerLazySingleton(() => CommonRepository());
  locator.registerLazySingleton(() => NotificationRepository());
  locator.registerLazySingleton(() => NewFeedRepository());

  locator.registerLazySingleton(() => ToolTipManager());
  locator.registerLazySingleton(() => AppsflyerUtil());
  locator.registerLazySingleton(() => PhotoProvider());
  locator.registerLazySingleton(() => AssetPathProvider());
  locator.registerLazySingleton(() => MyQuestionModel());
  locator.registerLazySingleton(() => TrackingManager());
  locator.registerLazySingleton(() => FacebookTracking());
  locator.registerLazySingleton(() => FireBaseRealTimeDatabaseUtil());

  locator.registerFactory(() => LoginModel());
  locator.registerFactory(() => OtpModel());
  locator.registerFactory(() => RegisterModel());
  locator.registerFactory(() => HomeModel());
  locator.registerFactory(() => ForgotPasswordModel());
  locator.registerFactory(() => UpdateInformationModel());
  locator.registerFactory(() => IntroModel());
  locator.registerFactory(() => CitiesModel());
  locator.registerFactory(() => HighlightModel());
  locator.registerFactory(() => CreateNewFeedModel());
  locator.registerFactory(() => ProfileModel());
  locator.registerFactory(() => PersonHighlightModel());
  locator.registerFactory(() => PersonFollowModel());
  locator.registerFactory(() => BlockUserModel());
  locator.registerFactory(() => PersonMessageModel());
  locator.registerFactory(() => ProfileTimelineModel());
  locator.registerFactory(() => ProfileFileModel());
  locator.registerFactory(() => DiscoveryModel());
  locator.registerFactory(() => ListHotModel());
  locator.registerFactory(() => DiscoveryNewFeedsModel());
  locator.registerFactory(() => DiscoveryNewFeedsMoreModel());
  locator.registerFactory(() => ListMoreOutStandingModel());
  locator.registerFactory(() => MyPostModel());
  locator.registerFactory(() => ListMoreGiftModel());
  locator.registerFactory(() => ListGiftModel());
  locator.registerFactory(() => CropImageModel());
  locator.registerFactory(() => ExchangeGiftModel());
  locator.registerFactory(() => ProfileCandyModel());
  locator.registerFactory(() => SendInformationGiftModel());
  locator.registerFactory(() => ListCheckinModel());
  locator.registerFactory(() => NotificationListModel());
  locator.registerFactory(() => NotificationDetailModel());
  locator.registerFactory(() => InAppWebViewModel());
  locator.registerFactory(() => UpdateInfoRequireModel());
  locator.registerFactory(() => UpdateInfoNonRequireModel());
  locator.registerFactory(() => PrivacyModel());
  locator.registerFactory(() => TestModel());
  locator.registerFactory(() => DatingListModel());
  locator.registerFactory(() => UserDatingBasicInfoModel());
  locator.registerFactory(() => DatingUserDetailModel());

  locator.registerFactory(() => TimelineListModel());
  locator.registerFactory(() => TimelineItemModel());
  locator.registerFactory(() => PostDetailModel());
  locator.registerFactory(() => VideoDetailModel());
  locator.registerFactory(() => AddInformationCreateDatingProfileModel());
  locator.registerFactory(() => ReviewInformationCreateDatingProfileModel());
  locator.registerFactory(() => FindFriendCreateDatingProfileModel());
  locator.registerFactory(() => VerifyDatingImageModel());
  locator.registerFactory(() => DatingFilterModel());
  locator.registerFactory(() => ProfileEditModel());
  locator.registerFactory(() => ProfileGenderModel());
  locator.registerFactory(() => FirstMessageModel());
  locator.registerFactory(() => ProfileDetailModel());
  locator.registerFactory(() => ListTopicHotModel());
  locator.registerFactory(() => GiveBearWidgetModel());
  locator.registerFactory(() => TopicListModel());
  locator.registerFactory(() => FilterTimelineModel());
  locator.registerFactory(() => DatingListItemModel());
  locator.registerFactory(() => ListMoreTopicModel());
  locator.registerFactory(() => ListMoreHotModel());
  locator.registerFactory(() => ListTypeDiscoveryModel());
  locator.registerFactory(() => EventSliderModel());
  locator.registerFactory(() => OutStandingEventModel());
  locator.registerFactory(() => DatingSettingModel());
  locator.registerFactory(() => DisplayNameModel());
  locator.registerFactory(() => BirthdayModel());
  locator.registerFactory(() => GenderModel());
  locator.registerFactory(() => ProfileImageModel());
  locator.registerFactory(() => ReplyQuestionModel());
  locator.registerFactory(() => ReplyQuestionItemModel());
  locator.registerFactory(() => WhoSuitsMeProfileModel());
  locator.registerFactory(() => WhoSuitsMeResultModel());
  locator.registerFactory(() => WhoSuitsMeHistoryModel());
  locator.registerFactory(() => SearchUserModel());
  locator.registerFactory(() => SearchModel());
  locator.registerFactory(() => SearchHashTagModel());
  locator.registerFactory(() => SearchThemeModel());
  locator.registerFactory(() => SearchNewFeedModel());
  locator.registerFactory(() => TemplateQuestionModel());
  locator.registerFactory(() => ReviewQuizResultModel());
  locator.registerFactory(() => CommentModel());
  locator.registerFactory(() => CommentChildrenModel());
  locator.registerFactory(() => FavoritePostModel());
  locator.registerFactory(() => PlayerModel());
  locator.registerFactory(() => VideoResizeModel());
  locator.registerFactory(() => ListGiftDiscoveryModel());
  locator.registerFactory(() => NotificationVoucherDetailModel());
  locator.registerFactory(() => NearYouModel());
  locator.registerFactory(() => ListKnowledgeModel());
  locator.registerFactory(() => EnterReferralModel());
  locator.registerFactory(() => DeteleAccountModel());
  locator.registerFactory(() => ReportModel());
  locator.registerFactory(() => UserSettingModel());
}
