# Uncomment this line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup


# ======================================GROUP PODS==========================================
def rx_pods
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxCocoa', '~> 6.2.0'
  pod 'XCoordinator', '~> 2.0'
  pod 'RxGesture', '~> 4.0.2'
end

def rx_swift_pods
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxRelay', '~> 6.2.0'
  pod 'RxCocoa', '~> 6.2.0'
end

def app_pods
  gif_pods
  component_pods
  secret_pods
  database_pods
  # pod 'Firebase/Core'
  pod 'MessageKit', :git => 'https://github.com/thanhphong-tran/messagekit'
  pod 'SwiftLinkPreview', :git => 'https://github.com/Netacom-NetAlo/SwiftLinkPreview', branch: 'dev_1.0'
  pod 'Kingfisher', '6.1.1'
  pod 'Carbon', '~> 1.0.0-rc.6'
  pod 'Localize-Swift', :git => 'http://gitlab.ecdc.vn/hieubui/nt-Localize-Swift'
  pod 'JitsiMeetSDK', git: 'https://github.com/Netacom-NetAlo/JitsiSDK-iOS.git', branch: 'dev_1.2'
  pod 'ZIPFoundation', '~> 0.9'
  pod 'FSCalendar', '2.8.2'
  #pod 'Firebase/Analytics', '6.21.0'
  #pod 'Firebase/Crashlytics', '6.21.0'
  # pod 'Firebase/Auth', '6.21.0'

  # Localization 2.0
  pod 'Localize-Swift', :git => 'http://gitlab.ecdc.vn/hieubui/nt-Localize-Swift'

  netalo_sdk_pods

  noti_netalo_pods
  socket_pods
  # Tracking
  pod 'FBSDKCoreKit', '~> 12.2.1'
   # pod 'AppsFlyerFramework', '5.2.0'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => "4.3.1"
  rx_pods
end

def database_pods
  pod 'RealmSwift', '10.12.0'
end

# Secret chat
def secret_pods
  pod 'SignalCoreKit', git: 'https://github.com/signalapp/SignalCoreKit.git', :commit => 'eea6884e55261bf157ad6054c72c3c51d7788d4c'
  pod 'AxolotlKit', git: 'https://github.com/signalapp/SignalProtocolKit.git', branch: 'master'
  pod 'HKDFKit', git: 'https://github.com/signalapp/HKDFKit.git'
  pod 'Curve25519Kit', git: 'https://github.com/signalapp/Curve25519Kit'
  pod 'GRKOpenSSLFramework', git: 'https://github.com/signalapp/GRKOpenSSLFramework', branch: 'mkirk/1.0.2t'
end

def socket_pods
  pod 'Socket.IO-Client-Swift', '14.0.0'
end

def testing_pods
  #    pod 'Quick', '~> 1.0'
  #    pod 'Nimble', '~> 7.0'
end

def resolver
  pod 'Resolver', tag: '1.4.4', git: 'https://github.com/thanhphong-tran/Resolver'
end
def component_pods
  #  rx_pods

  resolver
  pod 'Carbon', '~> 1.0.0-rc.6'
  pod 'Kingfisher', '6.1.1'
end

def netalo_sdk_pods
  pod 'NetaloSDKs', :git => 'http://gitlab.ecdc.vn/hieubui/NetaloSDKs', branch: 'lomo/sdk_main_v8'
end

def noti_netalo_pods
  pod  'NotificationSDK', :git => 'http://gitlab.ecdc.vn/hieubui/NotificationSDK', branch: 'lomo/sdk_noti_v8'
end

def notification_pods
  database_pods
  rx_swift_pods
  resolver
  noti_netalo_pods
  secret_pods
  socket_pods
  pod 'ZIPFoundation', '~> 0.9'
  pod 'Localize-Swift', :git => 'http://gitlab.ecdc.vn/hieubui/nt-Localize-Swift'
  pod 'JitsiMeetSDK', git: 'https://github.com/Netacom-NetAlo/JitsiSDK-iOS.git', branch: 'dev_1.2'
end


def gif_pods
  pod 'lottie-ios', '3.2.3'
end


target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  app_pods
  use_modular_headers!
end


target 'Runner-Dev' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  app_pods
  use_modular_headers!
end

target 'Runner-Stag' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  app_pods
  use_modular_headers!
end

target 'NotificationExtension' do
  notification_pods
end

target 'NotificationExtension-Dev' do
  notification_pods
end

target 'NotificationExtension-Stag' do
  notification_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ARCHS'] = 'arm64 x86_64'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',
      ## dart: PermissionGroup.calendar
      #         'PERMISSION_EVENTS=1',
      ## dart: PermissionGroup.reminders
      'PERMISSION_REMINDERS=1',
      ## dart: PermissionGroup.contacts
      # 'PERMISSION_CONTACTS=0',
      ## dart: PermissionGroup.camera
      'PERMISSION_CAMERA=1',
      ## dart: PermissionGroup.microphone
      'PERMISSION_MICROPHONE=1',
      ## dart: PermissionGroup.speech
      #         'PERMISSION_SPEECH_RECOGNIZER=1',
      ## dart: PermissionGroup.photos
      'PERMISSION_PHOTOS=1',
      ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
      'PERMISSION_LOCATION=1',
      ## dart: PermissionGroup.notification
      # 'PERMISSION_NOTIFICATIONS=0',
      ## dart: PermissionGroup.mediaLibrary
      #         'PERMISSION_MEDIA_LIBRARY=1',
      ## dart: PermissionGroup.sensors
      #         'PERMISSION_SENSORS=1'
      ]
    end
  end
end
